### PR TITLE
Update project

### PR DESCRIPTION
**Pull request by cstamas**
Changes:
* cut the crap with manual/service locator/guice nonsense, use SISU proper to assemble Aether
* use m-shade-p instead of m-assembly-p as former knows how to handle sisu index (since 3.3.0)
* update to latest Aether to gain new features like locking
* add some properties to make project IDE friendly (re java source/target)

### CODE REVIEW

**Comment by mosabua** [comment]
Sooo good.. you rock @cstamas  .. let me look at that shortly and cut a release in a bit

**Comment by mosabua** [comment]
Wdyt .. should I update to Java 11 as well .. 8 is dead anyway .. could even go for 17 maybe

**Comment by cstamas** [comment]
Am totally for. How about this "strategy":
* enforce latest Java LTS *to build*
* enforce latest Maven *to build*
* use Java9+ `release` flag to target Java11 (as it does much more than old source/target)

In short: enforce latest tooling, and use modern ways to target the runtime (then things like animal sniffer is not needed anymore). Something like this: https://github.com/apache/maven-indexer/pull/207

Indexer is first Maven project becoming Java11 due Lucene 9 that is 11 as well. 

Only question: am unsure does takari-lifecycle support `release` flag of compiler? Do you know from top of your head?

**Comment by cstamas** [comment]
Hm, seems it does: https://github.com/takari/takari-lifecycle/commit/5ff3fe1520075960c30673343fdf53af82d4b2da

**Comment by cstamas** [comment]
@mosabua if OK with this PR as is, please merge. IMHO Java11 is or should be different PR. Let's continue here https://github.com/simpligility/maven-repository-tools/issues/63

**Pull request merged**
