### PR TITLE
add credentials for source repository

### PR DESCRIPTION
**Pull request by boulik**

### CODE REVIEW

**Comment by mosabua** [comment]
Can you remove the resolver update as it is unrelated and already implemented in another branch and soon to be merged to master? Then I can take a look and pull this change in.

**Comment by boulik** [comment]
Sorry, my fault. 
Done

**Comment by mosabua** [comment]
No problem. Does this work like that even if no credentials are set?  Could you add something to the documentation?

**Comment by boulik** [comment]
Done.

**Comment by mosabua** [comment]
So it works transparently without credentials just as it did until now?

**Comment by boulik** [comment]
Yes.  If you dont use  credentials, AuthenticationBuilder doesnt create Authentication(or exactly returns null) so access to remote repository is without credentials.

**Comment by mosabua** [comment]
Thanks for confirming and the contribution.

**Pull request merged**
